version: '3.8'

services:
  backend:
    build: ./backend
    container_name: chatbot-backend-dev
    environment:
      - ENVIRONMENT=development
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: node:18-alpine
    container_name: chatbot-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend