name: Claude Code Review and Fix
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  claude-review-and-fix:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # コード修正のため write 権限が必要
      pull-requests: write
      issues: write
      id-token: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0     # 修正コミットのため full history が必要
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run Claude Code Review and Auto-fix
        id: claude-review
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          
          # 自動修正を含むプロンプト
          direct_prompt: |
            このPRをレビューし、以下を実行してください：
            
            1. **コードレビュー**: 問題を特定
            2. **自動修正**: 発見した問題を直接修正
            
            修正対象：
            - コードスタイルの統一
            - 明らかなバグの修正
            - パフォーマンスの改善
            - セキュリティ問題の修正
            - タイプエラーの修正
            - 不要なコードの削除
            
            修正後は修正内容を説明してください。
            重要な設計変更は修正せず、コメントで提案してください。
          
          # 修正に必要なツールを許可
          allowed_tools: |
            CreateOrEditFile(**/*)
            Bash(npm run lint --fix)
            Bash(npm run format)
            Bash(npm run typecheck)
